### ISSUE TITLE
Crash when trying to remove a step out of the order of setting

### ISSUE THREAD

**Issue by Noitapastori** [Juholei/Lukuinto-Spring-2015-editor#1]
After adding the start and end points and a few steps in between, attempting to remove a set step causes the application to crash, if the steps are not removed in the order of setting.

For example: If 3 steps are set, removing steps 1 or 2 first causes the application to crash. If the steps are removed in the order of 3 first, then 2, then 1, everything works okay.

Tested browsers: Latest versions of Chrome and Firefox

**Comment by Juholei** [comment]
Should be fixed in commit https://github.com/Juholei/Lukuinto-Spring-2015-editor/commit/437a1f21d8729a93ab95a78995759305c560051f
